/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.5.0.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as actions_post from "../actions/post";
import type * as actions_reset from "../actions/reset";
import type * as actions_vesta from "../actions/vesta";
import type * as pop from "../pop";
import type * as push from "../push";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  "actions/post": typeof actions_post;
  "actions/reset": typeof actions_reset;
  "actions/vesta": typeof actions_vesta;
  pop: typeof pop;
  push: typeof push;
}>;
